---
title: "D3.js Pres"
author: "A. Kuzmin & J. Lopez"
date: "March 21, 2018"
output: html_document
---

D3.js is a javascript library that uses documents based on data to create interactive & dynamic visualizations; the D3 stands for Data-Driven Document. Mike Bostock is one of the main developers for D3.js.

Javascript is a scripting language that is embedded in the HTML to make web pages interactive and dynamics.

Why use D3.js?
  - visualizations created with R are static, unless used in conjunction with a package,
  but even then, it won't be as customization as using javascript.
  - we'll show you why in a bit.
  - nonetheless, R produces great plots through packages like ggplot2
  - again, even with added packages, the customization are predetermined??
  - using javascript and the D3.js library makes binding javascript to data points

The structure of an HTML source code is as follows:
  <html> #embeds everything for the web page
  <head>...</head> #controls styling choices e.g. font, colour,etc.
  <body>...</body> #contains script that determines the visuals what will appear on web page
  </html>
  
<script>...</script> tags are contained in the body tags and is where the javascript is written

Scalable Vector Graphics (SVG) is an image format that is necessary for javascript to bind with its elements, and make them interactive.
  
2 Methods for creating interactive plots

  1. Use R for data processing and creating a graphic. The we export the graphic in SVG format and bind javascript to the elements we desire.
  Example of manually binding javascript: (http://vanhumbeecka.github.io/R-and-D3/svg-simple.html)
    - manually binding the javascript can be done of course, but it's a hassle
    - we have packages that complete the javascript binding for us, e.g. plotly
      - plotly examples: (http://vanhumbeecka.github.io/R-and-D3/plotly.html)
    
  2. Use R only for data processing & use javascript for entire visualization process. We get more customization & these can potentially result in some pretty graphics. Here is an example that may or may not have been tidied up in R: http://www.sciencemag.org/news/2017/04/here-s-visual-proof-why-vaccines-do-more-good-harm
  
Here's a gallery of different plots that use the D3.js library: https://github.com/d3/d3/wiki/Gallery
  
Both methods require an javascript knowledge.

Fortunately, there are R packages that produce some notable plots from the gallery above. E.g. networkD3, chorddiag,...
Mike Bostock has collaborted with others to release a few R packages that allow their users to create plots like the ones seen above. E.g. scatterD3, sunburstR, d3r

Final words:
- D3.js seems to make it easier to customize and integrate data at the same time. 
- utilizaing javascript may be more work than required for some basic plots -- we can just use R. 
- Unless, we wanted immense customization, perhaps using R or other packages like plotly may be enough.

Useful Resources:
https://www.w3schools.com/js/ (Javascript tutorials)
https://www.w3schools.com/html/default.asp (HTML tutorials)
https://www.rdocumentation.org/collaborators/name/Mike%20Bostock (Mike Bostock's packages)
https://github.com/d3 (D3 github repositories)